name: Publish

on:
  push:
    tags:
      - "*" # Publish on any new tag

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet tool restore
      - run: dotnet paket config add-token 'https://www.nuget.org' '${{ secrets.NUGET_TOKEN }}'
      - run: dotnet fake build
      - run: dotnet fake build -t Release
      - uses: mindsers/changelog-reader-action@v1.1.0
        id: changelog_reader
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md
      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*.nupkg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
